# Generated by Django 5.1.6 on 2025-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnsn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('B.E', 'B.E'), ('M.E', 'M.E'), ('PhD', 'PhD')], default='B.E', max_length=5),
        ),
    ]
